### ISSUE TITLE
release time of nuscenes-C

### ISSUE THREAD

**Issue by Crayon-new** [ldkong1205/Robo3D#2]
Hi, thanks for you great job!  Do you have a plan to release the code about nuscenes-c creating?

**Comment by ldkong1205** [comment]
Hi @Crayon-new, thanks for your interest in our work!

The code for generating corruptions on nuScenes will be made available soon. We will let you know once the code is ready. Meanwhile, you can first have a look at our generated nuScenes-C data, which can be downloaded from the following OpenDataLab page:
https://opendatalab.com/nuScenes-C/download

**Comment by qzhang852** [comment]
Hi, thank you for your excellent work! Do you have the plan to release the code of nuscenes-C generator in July as well?

**Comment by ldkong1205** [comment]
Hi @qzhang852, thanks for your interest in our work!

The code for generating nuScenes-C will be released in the coming days. We will let you know once the code is ready. Stay turned ~

**Comment by ldkong1205** [comment]
Hi @Crayon-new and @qzhang852, the code for generating nuScenes-C is ready. You can find our implementations at https://github.com/ldkong1205/Robo3D/tree/main/create.

Some data preparation details have been supplemented. Kindly refer to [DATA_PREPARE.md](https://github.com/ldkong1205/Robo3D/blob/main/docs/DATA_PREPARE.md) for preparing the datasets.

I am closing this issue now. Feel free to open a new one if you have any other questions!
