### ISSUE TITLE
镜面环境能检测吗

### ISSUE THREAD

**Issue by anning808** [ldkong1205/Robo3D#5]
我看在示例中有湿地的检测，所以好奇对湖面、玻璃幕墙、透明玻璃窗玻璃门这些检测会有什么样的效果。

**Comment by ldkong1205** [comment]
感谢您对我们这个工作的关注！

在这个工作中，我们主要讨论了针对天气条件和传感器损坏等比较广义的情况。您提到的`湖面`、`玻璃幕墙`、`透明玻璃窗`、`玻璃门`等比较具体的情况我们没有涉及。对3D检测器在这些情形下的表现的分析可能需要在有特定的数据集（例如专门针对半室内场景的点云数据集，包含了丰富的玻璃场景的信息）的情况下才能完成。

我们工作中和上述情形比较接近的就是`wet ground` (湿地)、`fog` (雾天)和`snow` (雪天)。对这三种情形，有专门的工作就点云的损坏生成进行了物理建模，详细的可以关注以下两篇论文：
- Martin Hahner, Christos Sakaridis, Dengxin Dai, and Luc Van Gool. "Fog Simulation on Real LiDAR Point Clouds for 3D Object Detection in Adverse Weather," ICCV, 2021. [论文链接](https://arxiv.org/abs/2108.05249)
- Martin Hahner, Christos Sakaridis, Mario Bijelic, Felix Heide, Fisher Yu, Dengxin Dai, and Luc Van Gool. ”LiDAR Snowfall Simulation for Robust 3D Object Detection,“ CVPR, 2022. [论文链接](https://arxiv.org/abs/2203.15118)

希望上述回答能帮助到您！
